# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(691, 599)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(510, 520, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 641, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 611, 301))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.hookList = QtWidgets.QListWidget(self.tab_2)
        self.hookList.setGeometry(QtCore.QRect(20, 30, 561, 192))
        self.hookList.setObjectName("hookList")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 250, 441, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.hookName = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.hookName.setObjectName("hookName")
        self.horizontalLayout.addWidget(self.hookName)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.hookUrl = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.hookUrl.setObjectName("hookUrl")
        self.horizontalLayout_2.addWidget(self.hookUrl)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.addButton = QtWidgets.QPushButton(self.tab_2)
        self.addButton.setGeometry(QtCore.QRect(480, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.delButton = QtWidgets.QPushButton(self.tab_2)
        self.delButton.setGeometry(QtCore.QRect(480, 290, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.delButton.setFont(font)
        self.delButton.setObjectName("delButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 400, 391, 181))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.to_channel = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.to_channel.setChecked(True)
        self.to_channel.setObjectName("to_channel")
        self.verticalLayout.addWidget(self.to_channel)
        self.to_here = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.to_here.setObjectName("to_here")
        self.verticalLayout.addWidget(self.to_here)
        self.to_none = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.to_none.setObjectName("to_none")
        self.verticalLayout.addWidget(self.to_none)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "送信"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "本文"))
        self.label.setText(_translate("Dialog", "送信先名"))
        self.label_4.setText(_translate("Dialog", "Webhook"))
        self.addButton.setText(_translate("Dialog", "追加"))
        self.delButton.setText(_translate("Dialog", "削除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "送信先設定"))
        self.groupBox.setTitle(_translate("Dialog", "通知設定"))
        self.to_channel.setText(_translate("Dialog", "@channel : チャンネルみんな"))
        self.to_here.setText(_translate("Dialog", "@here 今ランプついてるメンバーみんな"))
        self.to_none.setText(_translate("Dialog", "設定なし"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
